sudo: false

language: java

install: true

jdk:
  - oraclejdk8

services:
  - docker

cache:
  directories:
  - $HOME/.m2

install:
  - docker pull mongo

script:
 - mvn -f AccountantApp/pom.xml clean verify
 - mvn -f AccountantApp/pom.xml verify -Pdocker-compose
